/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextRequest, NextResponse } from "next/server";
import geminiModel from "@/lib/gemini";

export async function POST(request: NextRequest) {
    try {
        const { userQuestion } = await request.json();

        if (!userQuestion) {
            return NextResponse.json(
                { message: "Missing 'userQuestion' in request body" },
                { status: 400 }
            );
        }

        const prompt = `
You are an expert financial analyst and economics educator.
Your goal is to explain the concept of **${userQuestion}** in a clear, detailed, and structured way.

Please follow this format:
1. **Definition** — provide a concise definition.
2. **Key Concepts** — describe the main ideas or mechanisms behind it.
3. **Practical Strategies** — explain how individuals or businesses can apply this concept in real life.
4. **Example** — include one simple, illustrative example.

Use clear English with an educational tone.
`;

        const response = await geminiModel.generateContent(prompt);

        if (!response) {
            return NextResponse.json(
                { message: "No response from Gemini model" },
                { status: 500 }
            );
        }

        const text =
            response?.response?.candidates?.[0]?.content?.parts?.[0]?.text ||
            "No content generated by Gemini.";

        return NextResponse.json({ text });
    } catch (error: any) {
        console.error("Gemini API Error:", error);
        return NextResponse.json(
            { message: error.message || "Internal Server Error" },
            { status: 500 }
        );
    }
}
